{% set name = "vaex-server" %}
{% set version = "0.2.1" %}
{% set sha256 = "658bf3eb3cc859f693e5ef8c5efe806f8db3d3bc3676bfd8389cb0f50822e005" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - vaex-core
    - tornado >4.1
    - cachetools

test:
  imports:
    - vaex.server

about:
  home: https://www.github.com/maartenbreddels/vaex
  doc_url: https://docs.vaex.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Webserver and client for vaex for a remote dataset

extra:
  recipe-maintainers:
    - maartenbreddels
