{% set name = "vaex-server" %}
{% set version = "0.8.1" %}
{% set sha256 = "655e7702df77efdda3ba9527bc423a43c87d584407478af0dec8608398723934" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
    - wheel
  run:
    - python >=3.6
    - vaex-core >=4.7.0,<5.0.0
    - tornado >4.1
    - cachetools
    - fastapi
    - requests

test:
  imports:
    - vaex.server

about:
  home: https://github.com/vaexio/vaex
  dev_url: https://github.com/vaexio/vaex
  doc_url: https://vaex.io/docs/installing.html
  doc_source_url: https://github.com/vaexio/vaex/tree/master/docs
  license: MIT
  license_url: https://github.com/vaexio/vaex/blob/master/LICENSE.txt
  license_family: MIT
  license_file: LICENSE.txt
  summary: Webserver and client for vaex for a remote dataset
  description: Vaex is a high performance Python library for lazy Out-of-Core DataFrames (similar to Pandas), to visualize and explore big tabular datasets. 
 

extra:
  skip-lints:
    - avoid_noarch
    - missing_pip_check

  anaconda-services:
    ref:  https://anaconda.zendesk.com/agent/tickets/26940
    reason: "needed for building vaex"
    recipe-maintainers:
      - bkreider

  recipe-maintainers:
    - maartenbreddels
