travis:
  secure:
    BINSTAR_TOKEN: JeMr1x7Y5dLUedjaJx4k4OsY2QFuFTkIvmtLTJcnUyh/L4F5FWEb89ppdUZ9rNkO3Jhd2P2maBLd/5OODsqwd7ZLcFslB6xlraFtb4xZRUmXV+VXmD2TthveqrDAZMFKVc1kY/dk6XM0rwDZBHGxrWcjezQtvgFFycU+kH/zWnkBp+5bPi4Wr5LUF3iREurw4/1RjHpJe1j7XC+mZPNqarN8S7ht7O5K2C9O7WGnJJ4tgDHHcXh4Fp8Hmvh9Exq273O1Q7r7zOGDvVKhgjtnFfw2lTCOCR/Kt22spOQ6VCf1y3yBpwgg+de57RkbKU/HwU5lV0qHHohFHjp6HAaKVIvtgxR8iatUZBQEbSIZUBgI/Ymz7hsPJ3wkOyo7KJ1gFPcfqSZVkoFo9JkZMvQp0ZDkHUlVAxlX7PcWRYFAT3epHSUjpuOzscrFWjnRuUk5DbKFxQHX3avoOpTAU0vpiDLAIjCgUCER9MYUHifEZsc/wXQfEYyz7yYz7C14+dsiL/nZK1RVau9fx8MHoxHJ+w/5iTm1Cak8TapO9QPgjo/iTWsew7JTmomVO9B9UAscivKGheUSSmnRKWoxPevHtFskyCTFN1BPWkIGq+FoDjpXH/OW9jxF/odKjZFhc/Ua8ty7wWMG+Dgrl49TWCV2cXdBOxNi9B1TK5ZtevtKXO8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
