travis:
  secure:
    BINSTAR_TOKEN: SvU1QDVi+YwTlo8LtjAFGWxQH5rRqT6G7M3HxCNJYPNTWWRoyUFRiLUGySfbqE8PVvDKFyQWu0aB+JRlmghORbca7eVA5EeZMmMVCaNYlOsLmbVToxXopRHjUuwOPvQphBDTfSoSRdz2Et3uXDk9ifV1le5b4qRN6AsadYtMQSNGp0etyrwBo2fVhxAzdXOUFFfODDzKdAQSGK1f4QRQILQLTgDSFczIGi5iwQa5GxHl0u5geNaHts/WI9zwyLf3Fpp0qicB+F9XBpwysiO8gr3FdTWTcdJ4AqxinKSjx9oeEzhLvqdNwNBJgzCPfZIu3GONNX1BYTuabwdAdJploM7By+wEBmNMIRSXNZRIG7QWvRHk7jzxIThUsxyqLyhd23IwGx06NJ5eFct+FJULJmduq5FUpuYifl8njgMdNpgpBRehKpacSMjBDChPUwsbdBbP6XGmGG714rJ69OWLu7Qjh+DBn999RPD5dCjqg/1xCoKSVrx2oVvhjjZ0ZuOeBADhO3kuVLWGcG30+ip+r7oajun3ABXMkxvQF9cRWqez6fxqhMKPreQSmyqI4HIEWPQrtBSs1a/bJWHT8SxiXCAxLIsblU1oqFiW9QHv8FoClHH4kRhkvbkYFCVVheYq11kA2ZZHcAB0fkFx2FbWQ9mnHN+is9mQwMT5TVxsyoI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
