travis:
  secure:
    BINSTAR_TOKEN: rUgpk6N5j2ShMVLghxvbxw8JUsArGq0Fc6TpaoQBXG3glsEWxHfXdBD//lZjwsu7owxJKUyhnyW176xkZVIyNWR8hP1d3p33VyKjsdeXIYjXIiknOr3JFHDlCIm1qedG/tyHS6dWLe3WDUv1YmgDEbWgvuJd67T0VsRUWUkih5n0cpxChgyPoZtySz4XlKsXroCW63ijzcX+UKfgIb8AW4pLtscRemf0p2ChScuwD8sREci2oIlQU3m/mhZdoGrU5xZLk4LqLQppQq+v+n40eJ2SM3yM5jipKBI2L0LREUJWAdk3HI7ndLYNdoIVjPyUHHgdLU1X4wtSR0Knq2TR8EeBmOZnkAv0PuECZ2EeZ5wiGMK2Um0NdRfHrLHmuIIa4U3UmEmZKSW7i0VVQto/5/uIydPQtwIyK8bGtEMFLr0fJz95e0qvAspHjECHmQr49YEk3uOZ6fjKRZR5zVS2Phyzu1GPdX0XoTaZL6aV4QcvOqsX45zjwfcOiMK3U48LlYuZYceQ7O2gBDAoLUGI3SbP/wEISmO4be2trUCyOGRsridV7Os0fnZ9eW6VX8D2hxq6heEZMJ+5vXYBJINYqAF0kBFcPS26fbOW3LQ+ZilKbPruKhbkwDSDqv537shtDmYwdZGMrVSWEEipZV++IlGfEZ45aYLujvrJjfhZap0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
